### ISSUE TITLE
[Bug] Cannot reorder gallery images in WordPress 5.9

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-gallery#10]
### Describe the bug
Dragging gallery images to reorder them in the Edit Gallery interface does not work in WordPress 5.9.

**Console error:**
```
/wp-includes/js/media-views.min.js?ver=5.9
media-views.min.js?ver=5.9:2 Uncaught TypeError: Cannot read properties of undefined (reading 'args')
    at n.<anonymous> (media-views.min.js?ver=5.9:2:23305)
    at u (underscore.min.js?ver=1.13.1:2:16433)
```

### To Reproduce
1. Install BoldGrid Gallery in a WordPress 5.9 installation
2. Create a gallery and add images
3. Try to drag and reorder images

### Screenshots
![reorder-gallery-images](https://user-images.githubusercontent.com/17650704/151400597-5a43d977-43e4-4cee-a7d7-daac36316143.gif)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome

**Comment by bwmarkle** [comment]
I can't drag drop images in WordPress 5.9 with all plugins disabled. Can anyone else replicate?

**Comment by nicolepaschen** [comment]
I cannot replicate 
![drag-and-drop](https://user-images.githubusercontent.com/20601160/151406483-46542f0f-89b8-445a-af0e-85d43808d9f1.gif)

**Comment by nicolepaschen** [comment]
![gallery (1)](https://user-images.githubusercontent.com/20601160/151409399-4c47fd0f-7eff-4f73-8ea4-b825c39890d8.gif)

**Comment by joe9663** [comment]
I couldn't get the reordering to work with 2022 and WP Editor @nicolepaschen. Does the reordering only work for you if you upload the images? Selecting images from the Media Library when creating the gallery seems to break the functionality for me.

**Comment by nicolepaschen** [comment]
With WP 5.9 RC1 I can drag and drop but the images do not show in the PPB until I publish the page:
![gallery](https://user-images.githubusercontent.com/20601160/154707043-84034b0a-7a63-4911-a24f-2af359e52295.gif)

![chrome](https://user-images.githubusercontent.com/20601160/154707055-a7a81ccc-5a60-431e-8e38-6eb6a77d7983.gif)

**Comment by nicolepaschen** [comment]
We're on version 6.x now closing this ticket
